{
 "title": "CI/CD pipeline observability",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total pipeline",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ci_pipeline_status{exported_instance=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "count by pipeline status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "count by(status) (ci_pipeline_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Test Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ci_pipeline_test_errors{exported_instance=\"1\"}"
    }
   ]
  },
  {
   "title": "Tests Skipped",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ci_pipeline_test_skipped{exported_instance=\"1\"}"
    }
   ]
  },
  {
   "title": "Test Duration (seconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ci_pipeline_test_duration_seconds{exported_instance=\"1\"}"
    }
   ]
  },
  {
   "title": "test coverage percentage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ci_pipeline_coverage_percent{exported_instance=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Test Duration Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ci_pipeline_test_duration_seconds{exported_instance=\"1\"}"
    }
   ]
  },
  {
   "title": "Errors vs Skipped",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 10 },
   "targets": [
    {
     "expr": "ci_pipeline_test_errors{exported_instance=\"1\"}",
     "legendFormat": "errors"
    },
    { "expr": "ci_pipeline_test_skipped", "legendFormat": "skipped" }
   ]
  }
 ]
}